# Streamlit Cloud Secrets Configuration
# These should be configured in your Streamlit Cloud app's secrets management
# DO NOT commit actual secret values to version control

## JLG Provider Recommender Application Secrets

# Google Geocoding API (optional - for enhanced geocoding accuracy)
GOOGLE_MAPS_API_KEY = ""

# Alternative geocoding services (optional)
MAPBOX_ACCESS_TOKEN = ""
HERE_API_KEY = ""

# Database credentials (if connecting to external data sources in the future)
DATABASE_URL = ""

# Application environment settings
APP_ENVIRONMENT = "production"
DEBUG_MODE = false

# Security and rate limiting
ALLOWED_HOSTS = ["*.streamlit.app", "localhost"]
MAX_REQUESTS_PER_HOUR = 1000
MAX_GEOCODING_REQUESTS_PER_DAY = 2500

# Performance and caching
CACHE_TTL_HOURS = 24
MAX_CACHE_SIZE_MB = 100

# Analytics (optional)
GOOGLE_ANALYTICS_ID = ""

## Legacy API Credentials (for reference)
# Lead Docket Credentials
lead_docket_api_key = ""
lead_docket_base_api_endpoint = ""

# Filevine Credentials
