# Example Streamlit secrets for API access

## Lead Docket Credentials
lead_docket_api_key = "5629d96b-f6e2-4878-b257-1646b056b336"
lead_docket_base_api_endpoint = "https://jaklitschlawgroup.leaddocket.com/api/"


## Filevine Credentials